### PR TITLE
Sort in C locale

### PR DESCRIPTION
**Pull request by krlmlr**
Important for a stable `API` file.

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Oh, wait!

**Comment by gaborcsardi** [comment]
I would not load `withr`, because that might mess things up. (Usually it does not, but it is a good rule not to load any packages.)

Although we do load `pkgload` already....

OK, let's give it a go then. :)

**Comment by krlmlr** [comment]
How can we inline withr::with_collate() in sort_c()?

**Comment by gaborcsardi** [comment]
> How can we inline withr::with_collate() in sort_c()?

Just define a function within the function called by `r_vanilla`. 

But it is not crucial....

**Comment by krlmlr** [comment]
I remember you had a code that inlines all functions used by a function to make it self-contained. Couldn't we use it here?

**Comment by gaborcsardi** [comment]
I don't think that that was me. :) 

But the withr call is fine, seriously. If not, we'll handle it later.

**Comment by krlmlr** [comment]
How does install-github.me work? Who/what created the script that drives this service?

Anyway, if there's no automation to un-dep sort_c(), I'm fine with merging as is.

**Comment by gaborcsardi** [comment]
> How does install-github.me work? Who/what created the script that drives this service?

This is the script: https://github.com/r-pkgs/remotes/blob/master/install-github.R It is just the collation of the `remotes` files, and then a call to `install_github`: https://github.com/r-pkgs/remotes/blob/master/install-github.Rin

The web server just adds a function call to the requested package, and serves the R file.

> Anyway, if there's no automation to un-dep sort_c(), I'm fine with merging as is.

Jim wrote some inlining code for the (now dead) argufy package, but I don't think it is easily useable now. So, yeah, just merge it for now.

**Comment by krlmlr** [comment]
Thanks. Sorry to see argufy go.

**Comment by gaborcsardi** [comment]
> Thanks. Sorry to see argufy go.

Me too. We should have an R package cemetery organization on GitHub, or something..... I have a bunch of dead ones lying around....

**Pull request merged**
